### ISSUE TITLE
how to create .nds file?

### ISSUE THREAD

**Issue by JamesCzekajOld** [echojc/osu-ds#1]
Hi, i was wondering how to create the nds file, because build.bat does nothing!

Thanks!

**Comment by echojc** [comment]
If you open up build.bat, you see it just runs `make`. At the top of the Makefile, it checks that `DEVKITARM` is exported. That is part of devkitPro, which includes the tools you need to compile the .nds.

It looks like you can get some info here on how to install it here:
http://devkitpro.org/wiki/Getting_Started/devkitARM

Do note that it's been years since anyone's touched this code at all, so I can't guarantee it'll even compile now, but good luck!

**Comment by JamesCzekajOld** [comment]
Hi, I ran the build.bat and once it finished it didn't create a .nds file.
If you have a compiled nds file could you send it to me?

Thanks!

**Comment by echojc** [comment]
Sorry, I don't have a copy, nor the setup to compile this anymore.

**Comment by JamesCzekajOld** [comment]
Do you think I could download a 2009 version of devkitpro and it might work?

**Comment by echojc** [comment]
It might, yeah.

**Comment by JamesCzekajOld** [comment]
It didn't work, I don't know why!!! I installed the 2009 version of
devkitpro and when i run build.bat it goes through doing stuff then closes
and doesn't create the file! Is there anything else to do. Because I'd
really like to play osu! on ds.

**Comment by echojc** [comment]
If you were intending to actually play on a DS then I'm sorry to
disappoint. This project never made it past even the prototype stage. The
source was made available mainly for archival purposes.

Even if you have a .nds file, you probably won't be able to play anything
with it. It definitely doesn't read .osz files - you'll have to look at the
code to see what format it expects the audio to be in. For example, I
remember ditching MP3 because it takes up too much space.

**Comment by JamesCzekajOld** [comment]
k, i couldn't compile it anyway. Wait so you couldn't use it with a flash
card?

**Comment by JamesCzekajOld** [comment]
Also just a question, why did you end up not finishing the project?

**Comment by echojc** [comment]
I was inexperienced back then, and the DS is a very limited console. The
original games were highly optimized for size and efficiency, beyond what
you could feasibly do in a programmatic way.

This can run on a DS provided you set up your flash cart with the
appropriate files in a very specific format and in a specific directory
structure, both of which I can't remember anymore. If you want to find out,
you'll have to read the code.
